// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'dart:html';

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnr-_W-UZxfgW7tqrr3u9h4I5Yq5qLwsY',
    appId: '1:783028812678:web:7d67063a2f24157389ca07',
    messagingSenderId: '783028812678',
    projectId: 'nominal-group-app',
    authDomain: 'nominal-group-app.firebaseapp.com',
    storageBucket: 'nominal-group-app.appspot.com',
    measurementId: 'G-Q5MDGYTPJ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH8MBLtaJqN1mFN4NLTGKqJ-oZO0uTAJQ',
    appId: '1:783028812678:android:1809a3cd7992439389ca07',
    messagingSenderId: '783028812678',
    projectId: 'nominal-group-app',
    storageBucket: 'nominal-group-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0zhuM8DFA17FQNfTwFP9CccQO2TZBOBw',
    appId: '1:783028812678:ios:ccbb3b05c703930489ca07',
    messagingSenderId: '783028812678',
    projectId: 'nominal-group-app',
    storageBucket: 'nominal-group-app.appspot.com',
    iosBundleId: 'com.example.nominalGroup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0zhuM8DFA17FQNfTwFP9CccQO2TZBOBw',
    appId: '1:783028812678:ios:ccbb3b05c703930489ca07',
    messagingSenderId: '783028812678',
    projectId: 'nominal-group-app',
    storageBucket: 'nominal-group-app.appspot.com',
    iosBundleId: 'com.example.nominalGroup',
  );
}
